### ISSUE TITLE
USD Plugin is not reading UVs on geometry

### ISSUE THREAD

**Issue by morgan-cg** [dreamworksanimation/dwa_usd_plugins#4]
The USD plugin for Nuke seems to not be properly reading the UVs on geometry exported out of Houdini.

This test was done using Nuke 12.0v4 and USD 19.11.

I've tried a few different combinations of attribute remapping with the included tab on the readGeo node, but no success.

Below is the debugging printout of the readgeo node for my test geometry.

Also maybe worth noting, I connected your ViewGeoAttributes node to the readGeo node, which showed that the geo only had normals and "Cf" attributes.

Please let me know if there is any additional info I can provided that would be helpful.

Thanks!
Morgan

```
FuserGeoReader::geometry_engine(0x8d7cd20): rebuild_mask=2b: reload_prims=1, reload_points=0, reload_attribs=1, frame=206
 file='test3.usd', fuserIOClass='UsdIO'
 reader_frame=206, output_frame=206, selected nodes=1 num_objects=1, num_threads=1
 '/Scene/Set/MuseumInterior/Hallway/geo/Banco_01': , type='Mesh', HasPayload=0, IsActive=1, IsDefined=1, IsAbstract=0, isModel=0, isGprim=1, isScope=0 attribs[ accelerations, cornerIndices, cornerSharpnesses, creaseIndices, creaseLengths, creaseSharpnesses, doubleSided, extent, faceVaryingLinearInterpolation, faceVertexCounts, faceVertexIndices, holeIndices, interpolateBoundary, normals, orientation, points, primvars:class, primvars:class:indices, primvars:displayColor, primvars:displayColor:indices, primvars:displayOpacity, primvars:displayOpacity:indices, primvars:st, primvars:st:indices, primvars:uv, primvars:uv:indices, purpose, subdivisionScheme, triangleSubdivisionRule, velocities, visibility, xformOpOrder ]
 FuserUsdMesh::ctor('/Scene/Set/MuseumInterior/Hallway/geo/Banco_01') topo_variance=0 (default Purpose)[ accelerations, cornerIndices, cornerSharpnesses, creaseIndices, creaseLengths, creaseSharpnesses, doubleSided, extent, faceVaryingLinearInterpolation, faceVertexCounts, faceVertexIndices, holeIndices, interpolateBoundary, normals, orientation, points, primvars:class, primvars:class:indices, primvars:displayColor, primvars:displayColor:indices, primvars:displayOpacity, primvars:displayOpacity:indices, primvars:st, primvars:st:indices, primvars:uv, primvars:uv:indices, purpose, subdivisionScheme, triangleSubdivisionRule, velocities, visibility, xformOpOrder ]
FuserUsdMesh::_validateState(0xb579b50): for_real=1, time=206, m_local_bbox=[-3.35058 0.318408 -1.83118, -2.99723 1.34921 2.16528](0.353342 1.0308 3.99647), m_have_xform=0
 FuserUsdMesh::_execute(0xb579b50) target='GeoOpGeometryEngine' Mesh '/Scene/Set/MuseumInterior/Hallway/geo/Banco_01', xform disabled
 ----------------------------------------------------------------
 FuserUsdMesh::initializeMeshSample(0xb579b50): time=206, name='Banco_01', 'test3.usd'
 nFaces=577, nVerts=2308, nPoints=612
 --------------------------------------------------------------------------------------
 FuserUsdMesh::geoOpGeometryEngine(0xb579b50): obj=0, time=206, name='Banco_01', path='/Scene/Set/MuseumInterior/Hallway/geo/Banco_01', 'test3.usd'
 rebuild_mask=0x2b: reload_prims=1, reload_points=1, reload_attribs=1, m_local_bbox=[-3.35058 0.318408 -1.83118, -2.99723 1.34921 2.16528](0.353342 1.0308 3.99647), m_have_xform=0, mesh.subd_level=0, subd_render_level=0
 args: 'scene:path'=[/Scene/Set/MuseumInterior/Hallway/geo/Banco_01], 'fsr:node:path'=[/Scene/Set/MuseumInterior/Hallway/geo/Banco_01], 'scene:file:archive:context:hash'=[5965e73fec6229b4], 'scene:file:archive:context:id'=[9223001], 'reader:fps'=[24], 'reader:velocity_scale'=[1], 'fsr:node:name'=[Banco_01], 'reader:creation_mode'=[immediate], 'reader:attribute_mappings'=[], 'geo:read_debug'=[1], 'scene:node:selection:hash'=[a4ce5f9ee3bf4295], 'output_frame'=[206], 'reader:subd_force_enable'=[0], 'reader:subd_snap_to_limit'=[0], 'fsr:node:debug'=[1], 'scene:node:filter:hash'=[9625395cec878e5c], 'frame'=[206], 'fps'=[24], 'reader:color_facesets'=[0], 'scene:file'=[test3.usd], 'reader:subd_import_level'=[off], 'reader:subd_render_level'=[off], 'reader:debug'=[1], 'reader:use_geometry_colors'=[0], 'reader:proxy_lod_mode'=[proxy], 'fsr:node:directive'=[geo:node:auto-detect], 'reader:color_objects'=[0], 'reader:apply_matrix'=[1], 'reader:point_render_mode'=[pointclouds-spheres], 'reader:debug_attribs'=[1]
 FuserUsdMesh::dtor(0xb579b50) '/Scene/Set/MuseumInterior/Hallway/geo/Banco_01'
```

**Comment by jegstad-dwa** [comment]
Hi Morgan,

The FuserUsdMesh class is looking explicitly for 'primvars:uv', which your model has in it from reading the debug output. However the model also has 'primvars:st' which FuserUsdMesh is completely ignoring, so if 'primvars:uv' doesn't have useful data in it then that explains your problem.

I don't think uv attrib names are well defined in usd at this time so I'm unclear on what the 'default' primvar for uvs is, but am told that usd prefers 'st' but also supports 'uv'. Internally we use 'uv' so that's why it was set to that default.

So hardcoding the var name into that code was not a great idea and the FuserUsd plugin code needs to formally support the attribute mappings knob (our custom Alembic reader does support those mappings.)

Can you try changing this line to Pxr::TfToken("st") and see if that fixed your issue as a workaround?
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/plugin/FuserUsd/FuserUsdMesh.cpp#L729

Cheers,
-jonathan

**Comment by truant-bss** [comment]
Jonathan:
  Hello, my name is Jake Richards, I'll be helping out while Morgan gets his work from home setup.  This did fix the UV issue for a small test geo but I would also like to test it out on a more complex asset.  Unfortunately, I can't load many of our production assets until the issue with the files paths is resolved.  Do you think you'll have time to address that issue in the coming weeks?  Thank you again for all your work!

Jake

**Comment by jegstad-dwa** [comment]
Hi Jake,
Yeah no problem, I've still a couple weeks away from committing a bunch of changes but you can try a simple code change in the meantime to the getTrimmedPath() method:
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/02b283be1460ae6d02673fbfbd513cf9303aa14b/third_party/nuke/lib/Fuser/NodeIOInterface.cpp#L65

I'll post the proposed code changes on the other ticket:
https://github.com/dreamworksanimation/dwa_usd_plugins/issues/5

**Comment by truant-bss** [comment]
Jonathan:
  Thank you, we will give that a shot!

Jake

**Comment by jegstad-dwa** [comment]
Cool, please let me know if it works.

**Comment by jegstad-dwa** [comment]
@truant-bss @morgan-cg 

Uvs should read in now by default if the source primvar is named either 'st' or 'uv'. The usdReader now supports the attribute-mappings knob which allows multiple possible source names to map to the same output Nuke GeoInfo attribute name. The defaults for the usdReader are:
    st=uv, uv=uv
    normals=N
    displayColor=Cf
    displayOpacities=Of
    velocities=VEL

This is defined at:
https://github.com/dreamworksanimation/dwa_usd_plugins/blob/ab783c4a4c50c2b9a446fadf03fe8b51c12c093c/third_party/nuke/plugin/usdReader/usdReader.cpp#L57

You should be able to change these defaults by setting a knobDefaults for the usdReader class.

Give the new code a whirl.
-jonathan
